### ISSUE TITLE
TypeError: list object is not an iterator when running search()

### ISSUE THREAD

**Issue by ggirelli** [sebriois/biomart#22]
Hello!
Following the documentation I ran the code below:
```python
from biomart import BiomartServer
import pandas as pd

# Connect to biomart
server = BiomartServer( "http://www.ensembl.org/biomart" )
server.verbose = True

# Check available databases
#server.show_databases()

# Select Genes database
db = server.databases['ENSEMBL_MART_ENSEMBL']

# Check available datasets (species)
#db.show_datasets()

# Select H. sapiens dataset
ds = db.datasets['hsapiens_gene_ensembl']

response = ds.search()
```

And everything works properly until I run the `ds.search()` command, which triggers an error. Here is the output of the code above:
```python
[BiomartServer:'http://www.ensembl.org/biomart/martservice'] Fetching databases
[BiomartDatabase:'Ensembl Genes 89'] Fetching datasets
[BiomartDataset:'hsapiens_gene_ensembl'] Searching using following params:
{}
[BiomartDataset:'hsapiens_gene_ensembl'] Fetching attributes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 46, in <module>
  File "/usr/local/lib/python2.7/dist-packages/biomart/dataset.py", line 187, in search
    page = next(filter(lambda attr_page: attr_page.is_default, self._attribute_pages.values()))
TypeError: list object is not an iterator
```

Any idea of what I'm doing wrong?

Many thanks in advance!

p.s.: the `ds.count()` command works properly :)

**Comment by ggirelli** [comment]
Okay. The error is due to the fact that I was implementing everything in Python2.7. With Python3 everything works like a charm, thanks for developing this!

I'd suggest to remove support for Python2.7 from the Python package so that nobody installs it by mistake with `pip2`.

Cheers :)

**Comment by sebriois** [comment]
ha! will do. sorry about this.

thanks for the kind comment ;)

**Comment by ggirelli** [comment]
My pleasure! 😄  I submitted a pull request with the aforementioned README updates. I also implemented submitting the query through POST to overcome the GET URL length limit. Hope it helps! 😄 
Keep up the good work! 👍
