### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 749834-749837: ordinal not in range(128)

### ISSUE THREAD

**Issue by arkilis** [sebriois/biomart#4]
Error Msg:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 749834-749837: ordinal not in range(128)

File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1641, in feed

Not quite the other people meet the same error?

**Comment by sebriois** [comment]
check v0.7.1
