### ISSUE TITLE
Querying with filters not working for Ensembl datasets

### ISSUE THREAD

**Issue by alexbarrera** [sebriois/biomart#5]
I'm trying to perform a filtered query: 

    mus_ensembl = server.datasets['mmusculus_gene_ensembl']
    response = mus_ensembl.search({'filters': {'strand': '+'}})

which produces an empty response. Any ideas? I have tried different filters, none of them seem to be working.

**Comment by vladie0** [comment]
I'm having the same issue, makes querying impossible when you have to fetch the whole database

**Comment by sebriois** [comment]
FYI, you cannot query for strand using '+' and '-'. You should use 1 and -1 instead.

Regarding the slowness, yes, the module has to go through all databases under the biomart server to find the dataset you're trying to use.

You can give the module a little help by specifying the database name directly, something like this:
```python
import biomart
server = biomart.BiomartServer()
db = server.databases['ensembl']
mus_ensembl = db.datasets['mmusculus_gene_ensembl']
response = mus_ensembl.search({'filters': {'strand': 1}})  # instead of '+'
for line in response.iter_lines():
  print(line)
```

Sorry for the (very) late reply, hope this helps someone though :)
