### ISSUE TITLE
No module named server

### ISSUE THREAD

**Issue by kotoroshinoto** [sebriois/biomart#6]
Traceback (most recent call last):
  File "./maf_symbol_updater.py", line 3, in <module>
    from biomart import BiomartServer
  File "/usr/lib/python3.4/site-packages/biomart/__init__.py", line 1, in <module>
    from server import BiomartServer
ImportError: No module named 'server'

nonetheless: ls /usr/lib/python3.4/site-packages/biomart
attribute.py  database.py  dataset.py  filter.py  __init__.py  lib  __pycache__  server.py  test

does this not work with python3 at all, or is something else wrong?

**Comment by sebriois** [comment]
yeah, I had a similar issue recently when I started to move to python3. I have to look at the module and fix all these issues asap cause I also need it for work.

**Comment by sebriois** [comment]
ok version 0.7.1 should be usable with python3.

```bash
(test) sebriois@imac:~ [23:28:33] => python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import biomart
>>> s = biomart.BiomartServer()
>>> db = s.databases['unimart']
>>> uniprot = db.datasets['uniprot']
>>> response = uniprot.search({'filters': {'accession': 'Q9FMA1'}}, header=1)
>>> for line in response.iter_lines():
...   print(line)
... 
b'Gene name\tEntry name\tProtein name\tAccession'
b'PCMP-E13\tPP433_ARATH\tPentatricopeptide repeat-containing protein At5g56310\tQ9FMA1'
```
